### ISSUE TITLE
saving doesn't work

### ISSUE THREAD

**Issue by westlakem** [seattlerb/graph#19]
I tried to save a graph but both the JPG and PNG are empty
Here's the dot file that gets outputted
digraph 
  {
    "1"      [ label = "1" ];
    "2" [ label = "2" ];
    "3" [ label = "3" ];
    "4" [ label = "4" ];
    "5" [ label = "5" ];
    "6" [ label = "6" ];
    "1" -> "2";
    "2" -> "3";
    "2" -> "6";
    "3" -> "4";
    "4" -> "5";
  }

**Comment by zenspider** [comment]
I can't help you without a reproduction. Please provide some code.

**Comment by zenspider** [comment]
anything?

**Comment by westlakem** [comment]
Yep, my version of graphviz was corrupted... a fresh install fixed it.
