### ISSUE TITLE
Looking for help/documentation

### ISSUE THREAD

**Issue by brian-villanueva** [seattlerb/graph#21]
I've been through the gallery as well as the easy_visualization PDF and am having trouble understanding how to accomplish a couple things using graph.

1. How can I represent a single node with a black outline while giving it a different fill color? I see some graphs in the PDF file that make it clear that this is possible, but no code samples that show how to do it. (The closest I came was the "node_attribs << filled" example on page 32, but this loses the black outline of the shape.)

2. Is it possible to have a dashed line for an edge? I don't see any examples of this, but I do see "dotted" and "dashed" styles in the [source](https://github.com/seattlerb/graph/blob/cee98f90b5e127fa204c5036d58ec04e04475da5/lib/graph.rb#L55).

Apologies if the answers should be obvious... I'm a Ruby noob, so the syntax isn't clear to me.

**Comment by zenspider** [comment]
Starting with `gallery/simple_example.rb`:

1. I found this one a bit confusing. I think this might be considered a bug, that all `fill_*` colors used should imply `filled`:

```ruby
(filled + fill_lightblue) << node("c")
```

2.

```ruby
  dashed << edge("c", "a")
```

**Comment by zenspider** [comment]
Yeah. I think this should go in:

```diff
diff -r old/lib/graph.rb new/lib/graph.rb
--- old/lib/graph.rb
+++ new/lib/graph.rb
@@ -67,7 +67,7 @@
   (BOLD_COLORS + LIGHT_COLORS).each do |name|
     define_method(name) { color name }
     define_method("bg_#{name}") { bgcolor name }
-    define_method("fill_#{name}") { fillcolor name }
+    define_method("fill_#{name}") { filled + (fillcolor name) }
   end
 
   SHAPES.each do |name|
```

**Comment by zenspider** [comment]
Thank you for your issue. Graphviz is confusing at the best of times.

Let me know if you have any more questions. Close if satisfied.

**Comment by zenspider** [comment]
Anything?

**Comment by zenspider** [comment]
No response. Closing.

**Comment by brian-villanueva** [comment]
@zenspider sorry, i've been offline for a bit. I'll take a look... thanks for your responses!
